description: 
pack: aws
enabled: true
entry_point: run.py
name: apigateway_get_deployment
runner_type: python-script
parameters:
  action:
    default: get_deployment
    immutable: true
    type: string
  cls:
    default: apigateway
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  restApiId:
    type: string
    description: "The identifier of the RestApi resource for the Deployment resource to get information about."
    required: true
  deploymentId:
    type: string
    description: "The identifier of the Deployment resource to get information about."
    required: true
  embed:
    type: array
    description: "A query parameter to retrieve the specified embedded resources of the returned Deployment resource in the response. In a REST API call, this embed parameter value is a list of comma-separated strings, as in GET /restapis/{restapi_id}/deployments/{deployment_id}?embed=var1,var2. The SDK and other platform-dependent libraries might use a different format for the list. Currently, this request supports only retrieval of the embedded API summary this way. Hence, the parameter value must be a single-valued list containing only the 'apisummary' string. For example, GET /restapis/{restapi_id}/deployments/{deployment_id}?embed=apisummary."