---
description: 
pack: aws
enabled: true
entry_point: run.py
name: apigateway_get_deployments
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_deployments
    immutable: true
    type: string
  cls:
    default: apigateway
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  restApiId:
    type: string
    description: "The identifier of the RestApi resource for the collection of Deployment resources to get information about."
    required: true
  position:
    type: string
    description: "The position of the current Deployment resource in the collection to get information about."
  limit:
    type: integer
    description: "The maximum number of Deployment resources in the collection to get information about. The default limit is 25. It should be an integer between 1 - 500."