---
description: 
pack: aws
enabled: true
entry_point: run.py
name: application-autoscaling_register_scalable_target
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: register_scalable_target
    immutable: true
    type: string
  cls:
    default: application-autoscaling
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ServiceNamespace:
    type: string
    description: "The namespace of the AWS service. For more information, see AWS Service Namespaces in the Amazon Web Services General Reference."
    required: true
  ResourceId:
    type: string
    description: "The identifier of the resource associated with the scalable target. This string consists of the resource type and unique identifier.   ECS service - The resource type is service and the unique identifier is the cluster name and service name. Example: service/default/sample-webapp.   Spot fleet request - The resource type is spot-fleet-request and the unique identifier is the Spot fleet request ID. Example: spot-fleet-request/sfr-73fbd2ce-aa30-494c-8788-1cee4EXAMPLE.   EMR cluster - The resource type is instancegroup and the unique identifier is the cluster ID and instance group ID. Example: instancegroup/j-2EEZNYKUA1NTV/ig-1791Y4E1L8YI0.  "
    required: true
  ScalableDimension:
    type: string
    description: "The scalable dimension associated with the scalable target. This string consists of the service namespace, resource type, and scaling property.    ecs:service:DesiredCount - The desired task count of an ECS service.    ec2:spot-fleet-request:TargetCapacity - The target capacity of a Spot fleet request.    elasticmapreduce:instancegroup:InstanceCount - The instance count of an EMR Instance Group.  "
    required: true
  MinCapacity:
    type: integer
    description: "The minimum value to scale to in response to a scale in event. This parameter is required if you are registering a scalable target and optional if you are updating one."
  MaxCapacity:
    type: integer
    description: "The maximum value to scale to in response to a scale out event. This parameter is required if you are registering a scalable target and optional if you are updating one."
  RoleARN:
    type: string
    description: "The ARN of an IAM role that allows Application Auto Scaling to modify the scalable target on your behalf. This parameter is required when you register a scalable target and optional when you update one."