---
description: 
pack: aws
enabled: true
entry_point: run.py
name: cloudfront_get_streaming_distribution_config
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_streaming_distribution_config
    immutable: true
    type: string
  cls:
    default: cloudfront
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Id:
    type: string
    description: "The streaming distribution's ID."
    required: true