---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_list_deployment_instances
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_deployment_instances
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "The unique ID of a deployment."
    required: true
  nextToken:
    type: string
    description: "An identifier returned from the previous list deployment instances call. It can be used to return the next set of deployment instances in the list."
  instanceStatusFilter:
    type: array
    description: "A subset of instances to list by status:   Pending: Include those instance with pending deployments.   InProgress: Include those instance where deployments are still in progress.   Succeeded: Include those instances with successful deployments.   Failed: Include those instance with failed deployments.   Skipped: Include those instance with skipped deployments.   Unknown: Include those instance with deployments in an unknown state.  "