---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_batch_get_application_revisions
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: batch_get_application_revisions
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of an AWS CodeDeploy application about which to get revision information."
    required: true
  revisions:
    type: array
    description: "Information to get about the application revisions, including type and location."
    required: true