---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_batch_get_deployments
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: batch_get_deployments
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentIds:
    type: array
    description: "A list of deployment IDs, separated by spaces."