---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_create_deployment_config
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_deployment_config
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentConfigName:
    type: string
    description: "The name of the deployment configuration to create."
    required: true
  minimumHealthyHosts:
    type: object
    description: "The minimum number of healthy instances that should be available at any time during the deployment. There are two parameters expected in the input: type and value. The type parameter takes either of the following values:   HOST_COUNT: The value parameter represents the minimum number of healthy instances as an absolute value.   FLEET_PERCENT: The value parameter represents the minimum number of healthy instances as a percentage of the total number of instances in the deployment. If you specify FLEET_PERCENT, at the start of the deployment, AWS CodeDeploy converts the percentage to the equivalent number of instance and rounds up fractional instances.   The value parameter takes an integer. For example, to set a minimum of 95% healthy instance, specify a type of FLEET_PERCENT and a value of 95."