---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_list_deployment_groups
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_deployment_groups
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    required: true
  nextToken:
    type: string
    description: "An identifier returned from the previous list deployment groups call. It can be used to return the next set of deployment groups in the list."