---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_list_applications
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_applications
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  nextToken:
    type: string
    description: "An identifier returned from the previous list applications call. It can be used to return the next set of applications in the list."