---
description: 
pack: aws
enabled: true
entry_point: run.py
name: cognito-sync_set_identity_pool_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: set_identity_pool_configuration
    immutable: true
    type: string
  cls:
    default: cognito-sync
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  IdentityPoolId:
    type: string
    description: "A name-spaced GUID (for example, us-east-1:23EC4050-6AEA-7089-A2DD-08002EXAMPLE) created by Amazon Cognito. This is the ID of the pool to modify."
    required: true
  PushSync:
    type: object
    description: "Options to apply to this identity pool for push synchronization."
  CognitoStreams:
    type: object
    description: "Options to apply to this identity pool for Amazon Cognito streams."