---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_describe_configuration_recorder_status
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_configuration_recorder_status
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationRecorderNames:
    type: array
    description: "The name(s) of the configuration recorder. If the name is not specified, the action returns the current status of all the configuration recorders associated with the account."