---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_get_compliance_summary_by_resource_type
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_compliance_summary_by_resource_type
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ResourceTypes:
    type: array
    description: "Specify one or more resource types to get the number of resources that are compliant and the number that are noncompliant for each resource type. For this request, you can specify an AWS resource type such as AWS::EC2::Instance, and you can specify that the resource type is an AWS account by specifying AWS::::Account."