---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_delete_delivery_channel
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_delivery_channel
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DeliveryChannelName:
    type: string
    description: "The name of the delivery channel to delete."
    required: true