---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_get_compliance_details_by_resource
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_compliance_details_by_resource
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ResourceType:
    type: string
    description: "The type of the AWS resource for which you want compliance information."
    required: true
  ResourceId:
    type: string
    description: "The ID of the AWS resource for which you want compliance information."
    required: true
  ComplianceTypes:
    type: array
    description: "Filters the results by compliance. The allowed values are COMPLIANT, NON_COMPLIANT, and NOT_APPLICABLE."
  NextToken:
    type: string
    description: "The nextToken string returned on a previous page that you use to get the next page of results in a paginated response."