---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_get_resource_config_history
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_resource_config_history
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  resourceType:
    type: string
    description: "The resource type."
    required: true
  resourceId:
    type: string
    description: "The ID of the resource (for example., sg-xxxxxx)."
    required: true
  laterTime:
    type: string
    description: "The time stamp that indicates a later time. If not specified, current time is taken."
  earlierTime:
    type: string
    description: "The time stamp that indicates an earlier time. If not specified, the action returns paginated results that contain configuration items that start from when the first configuration item was recorded."
  chronologicalOrder:
    type: string
    description: "The chronological order for configuration items listed. By default the results are listed in reverse chronological order."
  limit:
    type: integer
    description: "The maximum number of configuration items returned on each page. The default is 10. You cannot specify a limit greater than 100. If you specify 0, AWS Config uses the default."
  nextToken:
    type: string
    description: "The nextToken string returned on a previous page that you use to get the next page of results in a paginated response."