---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_put_config_rule
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: put_config_rule
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRule:
    type: object
    description: ""
    required: true