---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_describe_delivery_channels
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_delivery_channels
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DeliveryChannelNames:
    type: array
    description: "A list of delivery channel names."