---
description: 
pack: aws
enabled: true
entry_point: run.py
name: discovery_describe_configurations
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_configurations
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  configurationIds:
    type: array
    description: "One or more configuration IDs."
    required: true