---
description: 
pack: aws
enabled: true
entry_point: run.py
name: ec2_revoke_security_group_ingress
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: revoke_security_group_ingress
    immutable: true
    type: string
  cls:
    default: ec2
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DryRun:
    type: boolean
    description: "Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is DryRunOperation. Otherwise, it is UnauthorizedOperation."
  GroupName:
    type: string
    description: "[EC2-Classic, default VPC] The name of the security group."
  GroupId:
    type: string
    description: "The ID of the security group. Required for a security group in a nondefault VPC."
  SourceSecurityGroupName:
    type: string
    description: "[EC2-Classic, default VPC] The name of the source security group. You can't specify this parameter in combination with the following parameters: the CIDR IP address range, the start of the port range, the IP protocol, and the end of the port range. For EC2-VPC, the source security group must be in the same VPC. To revoke a specific rule for an IP protocol and port range, use a set of IP permissions instead."
  SourceSecurityGroupOwnerId:
    type: string
    description: "[EC2-Classic] The AWS account ID of the source security group, if the source security group is in a different account. You can't specify this parameter in combination with the following parameters: the CIDR IP address range, the IP protocol, the start of the port range, and the end of the port range. To revoke a specific rule for an IP protocol and port range, use a set of IP permissions instead."
  IpProtocol:
    type: string
    description: "The IP protocol name (tcp, udp, icmp) or number (see Protocol Numbers). Use -1 to specify all."
  FromPort:
    type: integer
    description: "The start of port range for the TCP and UDP protocols, or an ICMP type number. For the ICMP type number, use -1 to specify all ICMP types."
  ToPort:
    type: integer
    description: "The end of port range for the TCP and UDP protocols, or an ICMP code number. For the ICMP code number, use -1 to specify all ICMP codes for the ICMP type."
  CidrIp:
    type: string
    description: "The CIDR IP address range. You can't specify this parameter when specifying a source security group."
  IpPermissions:
    type: array
    description: "A set of IP permissions. You can't specify a source security group and a CIDR IP address range."