---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_abort_environment_update
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: abort_environment_update
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentId:
    type: string
    description: "This specifies the ID of the environment with the in-progress update that you want to cancel."
  EnvironmentName:
    type: string
    description: "This specifies the name of the environment with the in-progress update that you want to cancel."