---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_update_environment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_environment
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application with which the environment is associated."
  EnvironmentId:
    type: string
    description: "The ID of the environment to update. If no environment with this ID exists, AWS Elastic Beanstalk returns an InvalidParameterValue error. Condition: You must specify either this or an EnvironmentName, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "
  EnvironmentName:
    type: string
    description: "The name of the environment to update. If no environment with this name exists, AWS Elastic Beanstalk returns an InvalidParameterValue error.  Condition: You must specify either this or an EnvironmentId, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "
  GroupName:
    type: string
    description: "The name of the group to which the target environment belongs. Specify a group name only if the environment's name is specified in an environment manifest and not with the environment name or environment ID parameters. See Environment Manifest (env.yaml) for details."
  Description:
    type: string
    description: "If this parameter is specified, AWS Elastic Beanstalk updates the description of this environment."
  Tier:
    type: object
    description: "This specifies the tier to use to update the environment. Condition: At this time, if you change the tier version, name, or type, AWS Elastic Beanstalk returns InvalidParameterValue error. "
  VersionLabel:
    type: string
    description: "If this parameter is specified, AWS Elastic Beanstalk deploys the named application version to the environment. If no such application version is found, returns an InvalidParameterValue error. "
  TemplateName:
    type: string
    description: "If this parameter is specified, AWS Elastic Beanstalk deploys this configuration template to the environment. If no such configuration template is found, AWS Elastic Beanstalk returns an InvalidParameterValue error. "
  SolutionStackName:
    type: string
    description: "This specifies the platform version that the environment will run after the environment is updated."
  OptionSettings:
    type: array
    description: "If specified, AWS Elastic Beanstalk updates the configuration set associated with the running environment and sets the specified configuration options to the requested value."
  OptionsToRemove:
    type: array
    description: "A list of custom user-defined configuration options to remove from the configuration set for this environment."