description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_delete_environment_configuration
runner_type: python-script
parameters:
  action:
    default: delete_environment_configuration
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application the environment is associated with."
    required: true
  EnvironmentName:
    type: string
    description: "The name of the environment to delete the draft configuration from."
    required: true