---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_swap_environment_cnam_es
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: swap_environment_cnam_es
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  SourceEnvironmentId:
    type: string
    description: "The ID of the source environment.  Condition: You must specify at least the SourceEnvironmentID or the SourceEnvironmentName. You may also specify both. If you specify the SourceEnvironmentId, you must specify the DestinationEnvironmentId. "
  SourceEnvironmentName:
    type: string
    description: "The name of the source environment.  Condition: You must specify at least the SourceEnvironmentID or the SourceEnvironmentName. You may also specify both. If you specify the SourceEnvironmentName, you must specify the DestinationEnvironmentName. "
  DestinationEnvironmentId:
    type: string
    description: "The ID of the destination environment.  Condition: You must specify at least the DestinationEnvironmentID or the DestinationEnvironmentName. You may also specify both. You must specify the SourceEnvironmentId with the DestinationEnvironmentId. "
  DestinationEnvironmentName:
    type: string
    description: "The name of the destination environment.  Condition: You must specify at least the DestinationEnvironmentID or the DestinationEnvironmentName. You may also specify both. You must specify the SourceEnvironmentName with the DestinationEnvironmentName. "