---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_describe_environment_managed_action_history
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_environment_managed_action_history
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentId:
    type: string
    description: "The environment ID of the target environment."
  EnvironmentName:
    type: string
    description: "The name of the target environment."
  NextToken:
    type: string
    description: "The pagination token returned by a previous request."
  MaxItems:
    type: integer
    description: "The maximum number of items to return for a single request."