description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticache_authorize_cache_security_group_ingress
runner_type: python-script
parameters:
  action:
    default: authorize_cache_security_group_ingress
    immutable: true
    type: string
  cls:
    default: elasticache
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  CacheSecurityGroupName:
    type: string
    description: ""
    required: true
  EC2SecurityGroupName:
    type: string
    description: ""
    required: true
  EC2SecurityGroupOwnerId:
    type: string
    description: ""
    required: true