---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_describe_environments
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_environments
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "If specified, AWS Elastic Beanstalk restricts the returned descriptions to include only those that are associated with this application."
  VersionLabel:
    type: string
    description: "If specified, AWS Elastic Beanstalk restricts the returned descriptions to include only those that are associated with this application version."
  EnvironmentIds:
    type: array
    description: "If specified, AWS Elastic Beanstalk restricts the returned descriptions to include only those that have the specified IDs."
  EnvironmentNames:
    type: array
    description: "If specified, AWS Elastic Beanstalk restricts the returned descriptions to include only those that have the specified names."
  IncludeDeleted:
    type: boolean
    description: "Indicates whether to include deleted environments:  true: Environments that have been deleted after IncludedDeletedBackTo are displayed.  false: Do not include deleted environments."
  IncludedDeletedBackTo:
    type: string
    description: " If specified when IncludeDeleted is set to true, then environments deleted after this date are displayed. "