---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_terminate_environment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: terminate_environment
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentId:
    type: string
    description: "The ID of the environment to terminate.  Condition: You must specify either this or an EnvironmentName, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "
  EnvironmentName:
    type: string
    description: "The name of the environment to terminate.  Condition: You must specify either this or an EnvironmentId, or both. If you do not specify either, AWS Elastic Beanstalk returns MissingRequiredParameter error. "
  TerminateResources:
    type: boolean
    description: "Indicates whether the associated AWS resources should shut down when the environment is terminated:    true: The specified environment as well as the associated AWS resources, such as Auto Scaling group and LoadBalancer, are terminated.    false: AWS Elastic Beanstalk resource management is removed from the environment, but the AWS resources continue to operate.    For more information, see the  AWS Elastic Beanstalk User Guide.    Default: true   Valid Values: true | false "
  ForceTerminate:
    type: boolean
    description: "Terminates the target environment even if another environment in the same group is dependent on it."