---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_compose_environments
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: compose_environments
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application to which the specified source bundles belong."
  GroupName:
    type: string
    description: "The name of the group to which the target environments belong. Specify a group name only if the environment name defined in each target environment's manifest ends with a + (plus) character. See Environment Manifest (env.yaml) for details."
  VersionLabels:
    type: array
    description: "A list of version labels, specifying one or more application source bundles that belong to the target application. Each source bundle must include an environment manifest that specifies the name of the environment and the name of the solution stack to use, and optionally can specify environment links to create."