---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_describe_environment_managed_actions
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_environment_managed_actions
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  EnvironmentName:
    type: string
    description: "The name of the target environment."
  EnvironmentId:
    type: string
    description: "The environment ID of the target environment."
  Status:
    type: string
    description: "To show only actions with a particular status, specify a status."