---
description: 
pack: aws
enabled: true
entry_point: run.py
name: emr_list_security_configurations
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_security_configurations
    immutable: true
    type: string
  cls:
    default: emr
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Marker:
    type: string
    description: "The pagination token that indicates the set of results to retrieve."