---
description: 
pack: aws
enabled: true
entry_point: run.py
name: es_update_elasticsearch_domain_config
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_elasticsearch_domain_config
    immutable: true
    type: string
  cls:
    default: es
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DomainName:
    type: string
    description: "The name of the Elasticsearch domain that you are updating. "
    required: true
  ElasticsearchClusterConfig:
    type: object
    description: "The type and number of instances to instantiate for the domain cluster."
  EBSOptions:
    type: object
    description: "Specify the type and size of the EBS volume that you want to use. "
  SnapshotOptions:
    type: object
    description: "Option to set the time, in UTC format, for the daily automated snapshot. Default value is 0 hours. "
  AdvancedOptions:
    type: object
    description: "Modifies the advanced option to allow references to indices in an HTTP request body. Must be false when configuring access to individual sub-resources. By default, the value is true. See Configuration Advanced Options for more information."
  AccessPolicies:
    type: string
    description: "IAM access policy as a JSON-formatted string."