---
description: 
pack: aws
enabled: true
entry_point: run.py
name: gamelift_update_runtime_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_runtime_configuration
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  FleetId:
    type: string
    description: "Unique identifier of the fleet to update runtime configuration for."
    required: true
  RuntimeConfiguration:
    type: object
    description: "Instructions for launching server processes on each instance in the fleet. The runtime configuration for a fleet has a collection of server process configurations, one for each type of server process to run on an instance. A server process configuration specifies the location of the server executable, launch parameters, and the number of concurrent processes with that configuration to maintain on each instance."
    required: true