---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_delete_application_output
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_application_output
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Amazon Kinesis Analytics application name."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "Amazon Kinesis Analytics application version. You can use the DescribeApplication operation to get the current application version. If the version specified is not the current version, the ConcurrentModificationException is returned. "
    required: true
  OutputId:
    type: string
    description: "The ID of the configuration to delete. Each output configuration that is added to the application, either when the application is created or later using the AddApplicationOutput operation, has a unique ID. You need to provide the ID to uniquely identify the output configuration that you want to delete from the application configuration. You can use the DescribeApplication operation to get the specific OutputId. "
    required: true