---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_add_application_reference_data_source
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: add_application_reference_data_source
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Name of an existing application."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "Version of the application for which you are adding the reference data source. You can use the DescribeApplication operation to get the current application version. If the version specified is not the current version, the ConcurrentModificationException is returned."
    required: true
  ReferenceDataSource:
    type: object
    description: "The reference data source can be an object in your Amazon S3 bucket. Amazon Kinesis Analytics reads the object and copies the data into the in-application table that is created. You provide an S3 bucket, object key name, and the resulting in-application table that is created. You must also provide an IAM role with the necessary permissions that Amazon Kinesis Analytics can assume to read the object from your S3 bucket on your behalf."
    required: true