---
description: 
pack: aws
enabled: true
entry_point: run.py
name: lambda_get_function_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_function_configuration
    immutable: true
    type: string
  cls:
    default: lambda
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  FunctionName:
    type: string
    description: "The name of the Lambda function for which you want to retrieve the configuration information.  You can specify a function name (for example, Thumbnail) or you can specify Amazon Resource Name (ARN) of the function (for example, arn:aws:lambda:us-west-2:account-id:function:ThumbNail). AWS Lambda also allows you to specify a partial ARN (for example, account-id:Thumbnail). Note that the length constraint applies only to the ARN. If you specify only the function name, it is limited to 64 character in length. "
    required: true
  Qualifier:
    type: string
    description: "Using this optional parameter you can specify a function version or an alias name. If you specify function version, the API uses qualified function ARN and returns information about the specific function version. If you specify an alias name, the API uses the alias ARN and returns information about the function version to which the alias points. If you don't specify this parameter, the API uses unqualified function ARN, and returns information about the $LATEST function version."