---
description: 
pack: aws
enabled: true
entry_point: run.py
name: rds_authorize_db_security_group_ingress
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: authorize_db_security_group_ingress
    immutable: true
    type: string
  cls:
    default: rds
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DBSecurityGroupName:
    type: string
    description: "The name of the DB security group to add authorization to."
    required: true
  CIDRIP:
    type: string
    description: "The IP range to authorize."
  EC2SecurityGroupName:
    type: string
    description: " Name of the EC2 security group to authorize. For VPC DB security groups, EC2SecurityGroupId must be provided. Otherwise, EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId must be provided. "
  EC2SecurityGroupId:
    type: string
    description: " Id of the EC2 security group to authorize. For VPC DB security groups, EC2SecurityGroupId must be provided. Otherwise, EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId must be provided. "
  EC2SecurityGroupOwnerId:
    type: string
    description: " AWS account number of the owner of the EC2 security group specified in the EC2SecurityGroupName parameter. The AWS Access Key ID is not an acceptable value. For VPC DB security groups, EC2SecurityGroupId must be provided. Otherwise, EC2SecurityGroupOwnerId and either EC2SecurityGroupName or EC2SecurityGroupId must be provided. "