---
description: 
pack: aws
enabled: true
entry_point: run.py
name: redshift_authorize_cluster_security_group_ingress
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: authorize_cluster_security_group_ingress
    immutable: true
    type: string
  cls:
    default: redshift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ClusterSecurityGroupName:
    type: string
    description: "The name of the security group to which the ingress rule is added."
    required: true
  CIDRIP:
    type: string
    description: "The IP range to be added the Amazon Redshift security group."
  EC2SecurityGroupName:
    type: string
    description: "The EC2 security group to be added the Amazon Redshift security group."
  EC2SecurityGroupOwnerId:
    type: string
    description: "The AWS account number of the owner of the security group specified by the EC2SecurityGroupName parameter. The AWS Access Key ID is not an acceptable value.  Example: 111122223333 "