---
description: 
pack: aws
enabled: true
entry_point: run.py
name: s3_list_bucket_metrics_configurations
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_bucket_metrics_configurations
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "The name of the bucket containing the metrics configurations to retrieve."
    required: true
  ContinuationToken:
    type: string
    description: "The marker that is used to continue a metrics configuration listing that has been truncated. Use the NextContinuationToken from a previously truncated list response to continue the listing. The continuation token is an opaque value that Amazon S3 understands."