---
description: 
pack: aws
enabled: true
entry_point: run.py
name: s3_put_bucket_accelerate_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: put_bucket_accelerate_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "Name of the bucket for which the accelerate configuration is set."
    required: true
  AccelerateConfiguration:
    type: object
    description: "Specifies the Accelerate Configuration you want to set for the bucket."
    required: true