description: 
pack: aws
enabled: true
entry_point: run.py
name: s3_put_bucket_inventory_configuration
runner_type: run-python
parameters:
  action:
    default: put_bucket_inventory_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "The name of the bucket where the inventory configuration will be stored."
    required: true
  Id:
    type: string
    description: "The ID used to identify the inventory configuration."
    required: true
  InventoryConfiguration:
    type: structure
    description: "Specifies the inventory configuration."
    required: true