description: 
pack: aws
enabled: true
entry_point: run.py
name: s3_put_bucket_notification_configuration
runner_type: run-python
parameters:
  action:
    default: put_bucket_notification_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: ""
    required: true
  NotificationConfiguration:
    type: structure
    description: ""
    required: true