description: 
pack: aws
enabled: true
entry_point: run.py
name: sns_delete_platform_application
runner_type: run-python
parameters:
  action:
    default: delete_platform_application
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  PlatformApplicationArn:
    type: string
    description: ""
    required: true