---
description: 
pack: aws
enabled: true
entry_point: run.py
name: sns_set_platform_application_attributes
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: set_platform_application_attributes
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  PlatformApplicationArn:
    type: string
    description: "PlatformApplicationArn for SetPlatformApplicationAttributes action."
    required: true
  Attributes:
    type: object
    description: "A map of the platform application attributes. Attributes in this map include the following:    PlatformCredential -- The credential received from the notification service. For APNS/APNS_SANDBOX, PlatformCredential is private key. For GCM, PlatformCredential is 'API key'. For ADM, PlatformCredential is 'client secret'.    PlatformPrincipal -- The principal received from the notification service. For APNS/APNS_SANDBOX, PlatformPrincipal is SSL certificate. For GCM, PlatformPrincipal is not applicable. For ADM, PlatformPrincipal is 'client id'.    EventEndpointCreated -- Topic ARN to which EndpointCreated event notifications should be sent.    EventEndpointDeleted -- Topic ARN to which EndpointDeleted event notifications should be sent.    EventEndpointUpdated -- Topic ARN to which EndpointUpdate event notifications should be sent.    EventDeliveryFailure -- Topic ARN to which DeliveryFailure event notifications should be sent upon Direct Publish delivery failure (permanent) to one of the application's endpoints.    SuccessFeedbackRoleArn -- IAM role ARN used to give Amazon SNS write access to use CloudWatch Logs on your behalf.    FailureFeedbackRoleArn -- IAM role ARN used to give Amazon SNS write access to use CloudWatch Logs on your behalf.    SuccessFeedbackSampleRate -- Sample rate percentage (0-100) of successfully delivered messages.  "
    required: true