---
description: 
pack: aws
enabled: true
entry_point: run.py
name: sns_list_platform_applications
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_platform_applications
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  NextToken:
    type: string
    description: "NextToken string is used when calling ListPlatformApplications action to retrieve additional records that are available after the first page results."