---
description: 
pack: aws
enabled: true
entry_point: run.py
name: sns_get_platform_application_attributes
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_platform_application_attributes
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  PlatformApplicationArn:
    type: string
    description: "PlatformApplicationArn for GetPlatformApplicationAttributesInput."
    required: true